language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
addons:
  sonarcloud:
    organization: "eklera"
script: python3 regexp.py || python regexp.py
after_success:
  - sonar-scanner